name: Unit Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install GCC 8
      run: |
        sudo apt-get install gcc-8 g++-8

    - name: Install Conan
      run: |
        sudo pip install conan

    - name: Install LLVM
      run: |
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 12

    - name: Build AccSynt
      run: |
        mkdir build
        cd build
        cmake \
              -DCMAKE_BUILD_TYPE=Debug \
              -DCMAKE_C_COMPILER=gcc-8 \
              -DCMAKE_CXX_COMPILER=g++-8 \
              -DLLVM_DIR=`llvm-config-12 --cmakedir` \
              ../src
        make -j `nproc`

    - name: Test
      working-directory: build
      run: make test
